algoritmo "semnome"
// 29) Ler 3 valores (considere que não serão informados valores iguais) e escrever a soma dos 2
//maiores.
var
a , b , c : inteiro
inicio
Escreva("Digite um valor A")
Leia(a)
Escreva("Digite um valor B")
Leia(b)
Escreva("Digite um valor C")
Leia(c)
Se (a>c) e (b>c)entao
Escreva("A soma dos 2 maiores é igual a ",a+b)
Senao
Se (b>a) e (c>a)entao
Escreva("A soma dos 2 maiores é igual a ",b+c)
Senao
Escreva("A soma dos 2 maiores é igual a ",a+c)
Fimse
Fimse
fimalgoritmo
