algoritmo "semnome"
// 28) Ler 3 valores (considere que não serão informados valores iguais) e escrever o maior deles.
var
a , b , c : inteiro
inicio
Escreva("Digite um valor A")
Leia(a)
Escreva("Digite um valor B")
Leia(b)
Escreva("Digite um  valor C")
Leia(c)
Se (a>b) e (a>c)entao
Escreva("O valor A é o maior")
Senao
Se(b>a) e (b>c)entao
Escreva("O valor B é o maior")
Senao
Escreva("O valor C é o maior")
Fimse
Fimse
fimalgoritmo
