algoritmo "semnome"
// 4) Reescreva as instruções abaixo com o mínimo de parênteses possível, mas sem alterar o
//resultado:
var
a , b , c , d : real
inicio

a := 6*(3+2)
escreval("A = ",a)
b := 2+(6*(3+2))
escreval("B = ",b)
b := 2+6*(3+2)
escreval("B = ",b)
c := 2+(3*6)/(2+4)
escreval("C = ",c)
c := 2+3*6/(2+4)
escreval("C = ",c)
d := 2*(8/(3+1))
escreval("D = ",d)
d := 2*8/(3+1)
escreval("D = ",d)

fimalgoritmo
